# Generated by Django 4.0.3 on 2022-08-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_skil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skil',
            new_name='skill',
        ),
    ]
