# Generated by Django 4.0.3 on 2022-08-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0005_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='maps',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='perm',
            field=models.CharField(blank=True, choices=[('True', 'Ruxsat berish'), ('', 'Rad etish')], max_length=5, null=True),
        ),
    ]
