# Generated by Django 4.0.3 on 2022-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('perm', models.CharField(choices=[('True', 'Ruxsat berish'), ('False', 'Rad etish')], max_length=5)),
                ('maps', models.CharField(max_length=250)),
            ],
        ),
    ]
